from setuptools import setup, find_packages

setup(name='innout',
      version='0.0.1',
      description='In-N-Out ICLR 2021',
      url='https://github.com/p-lambda/in-n-out',
      author='Sang Michael Xie, Ananya Kumar, Robbie Jones',
      author_email='xie@cs.stanford.edu',
      packages=find_packages('.'),
      install_requires=[
        'matplotlib',
        'numpy',
        'torch==1.4.0',
        'torchvision==0.5.0',
        'tqdm',
        'pyyaml',
        'requests',
        'wandb',
        'pandas',
        'h5py',
        'strconv',
        'scikit-learn',
        'scipy',
        'cdsapi',
      ])
